// Generated file by FlutterFire CLI.
// DO NOT EDIT: This file is auto-generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYoV1ZDwLKI-BHexFMIQZNGbJizA8Erzg',
    appId: '1:412640823732:web:01a5f3d7ebbabff9c48ae1',
    messagingSenderId: '412640823732',
    projectId: 'spaceshare-72fc5',
    authDomain: 'spaceshare-72fc5.firebaseapp.com',
    databaseURL: 'https://spaceshare-72fc5-default-rtdb.firebaseio.com',
    storageBucket: 'spaceshare-72fc5.firebasestorage.app',
    measurementId: 'G-B1QJ9SX6PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGjVL4WwMRCXHnHfw5QIkbgAWmEeyrtI',
    appId: '1:412640823732:android:234d72bdbbdfcf9fc48ae1',
    messagingSenderId: '412640823732',
    projectId: 'spaceshare-72fc5',
    databaseURL: 'https://spaceshare-72fc5-default-rtdb.firebaseio.com',
    storageBucket: 'spaceshare-72fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXwPlqyUhQF7PGWpID1xox79jhwkEBvho',
    appId: '1:412640823732:ios:2b3dfe3513e370dfc48ae1',
    messagingSenderId: '412640823732',
    projectId: 'spaceshare-72fc5',
    databaseURL: 'https://spaceshare-72fc5-default-rtdb.firebaseio.com',
    storageBucket: 'spaceshare-72fc5.firebasestorage.app',
    iosBundleId: 'com.spaceshare.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYoV1ZDwLKI-BHexFMIQZNGbJizA8Erzg',
    appId: '1:412640823732:macos:2b3dfe3513e370dfc48ae1',
    messagingSenderId: '412640823732',
    projectId: 'spaceshare-72fc5',
    databaseURL: 'https://spaceshare-72fc5-default-rtdb.firebaseio.com',
    storageBucket: 'spaceshare-72fc5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYoV1ZDwLKI-BHexFMIQZNGbJizA8Erzg',
    appId: '1:412640823732:web:f152d72ce46a3934c48ae1',
    messagingSenderId: '412640823732',
    projectId: 'spaceshare-72fc5',
    authDomain: 'spaceshare-72fc5.firebaseapp.com',
    databaseURL: 'https://spaceshare-72fc5-default-rtdb.firebaseio.com',
    storageBucket: 'spaceshare-72fc5.firebasestorage.app',
    measurementId: 'G-N4TFQS33LY',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}